/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        login: [];
        'login.store': [];
        logout: [];
        'password.request': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.email': [];
        'password.update': [];
        register: [];
        'register.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        'password.confirmation': [];
        'password.confirm.store': [];
        'two-factor.login': [];
        'two-factor.login.store': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'two-factor.regenerate-recovery-codes': [];
        home: [];
        dashboard: [];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        'user-password.edit': [];
        'user-password.update': [];
        'appearance.edit': [];
        'two-factor.show': [];
        'habits.index': [];
        'habits.create': [];
        'habits.store': [];
        'habits.show': [
            {
                name: 'habit';
                required: true;
                binding: 'id';
            },
        ];
        'habits.edit': [
            {
                name: 'habit';
                required: true;
                binding: 'id';
            },
        ];
        'habits.update': [
            {
                name: 'habit';
                required: true;
                binding: 'id';
            },
        ];
        'habits.destroy': [
            {
                name: 'habit';
                required: true;
                binding: 'id';
            },
        ];
        'habits.entries.index': [
            {
                name: 'habit';
                required: true;
            },
        ];
        'habits.entries.store': [
            {
                name: 'habit';
                required: true;
                binding: 'id';
            },
        ];
        'habits.entries.show': [
            {
                name: 'habit';
                required: true;
            },
            {
                name: 'entry';
                required: true;
            },
        ];
        'habits.entries.update': [
            {
                name: 'habit';
                required: true;
            },
            {
                name: 'entry';
                required: true;
            },
        ];
        'habits.entries.destroy': [
            {
                name: 'habit';
                required: true;
            },
            {
                name: 'entry';
                required: true;
            },
        ];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
